using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.UI;
public class Player : MonoBehaviour
{
    public static Player Instance;

    [SerializeField] private Transform[] weaponContainers;
    [SerializeField] private Transform magnetArea;

    [SerializeField] private float speed = 0.025f;

    [Header("UI")]
    [SerializeField] private VariableJoystick joystick;
    [SerializeField] private GameObject canvasGO;
    [SerializeField] private Image hpGuage;
    [SerializeField] private Image expGuage;
    [SerializeField] private StatSlot[] statSlots;
    [SerializeField] private StateToggle magnetToggle;

    private Dictionary<PlayerStat, StatSlot> statDictionary;

    public int Level => statDictionary[PlayerStat.Level].value;
    public int killCount => statDictionary[PlayerStat.Kill].value;
    public int Strength => statDictionary[PlayerStat.Strength].value;
    public int weaponALevel => statDictionary[PlayerStat.WeaponA].value;
    public int weaponBLevel => statDictionary[PlayerStat.WeaponB].value;
    public int weaponCLevel => statDictionary[PlayerStat.WeaponC].value;
    public int weaponDLevel => statDictionary[PlayerStat.WeaponD].value;

    public Vector3 moveVec { get; private set; }
    public Animator animator { get; private set; }
    public SpriteRenderer spriteRenderer { get; private set; }

    private SpriteRenderer magnetRenderer;
    private bool isMagnetVisible = false;
    private void Awake()
    {
        Instance = this;

        // 캐릭터 선택
        GameObject character = GameObject.Instantiate(Resources.Load<GameObject>("Players/Character_" + StaticValues.playerCharacterNum), transform);
        animator = character.GetComponent<Animator>();
        spriteRenderer = character.GetComponent<SpriteRenderer>();

        magnetRenderer = magnetArea.GetComponent<SpriteRenderer>();
        magnetRenderer.enabled = isMagnetVisible;
    }
    private void Start()
    {
        canvasGO.SetActive(false);

        // 스탯 초기화
        statDictionary = new Dictionary<PlayerStat, StatSlot>();
        foreach (StatSlot slot in statSlots)
        {
            statDictionary.Add(slot.type, slot);
        }
        statDictionary[PlayerStat.Level].Init(1);
        statDictionary[PlayerStat.Kill].Init(0);
        statDictionary[PlayerStat.Magnet].Init(0);
        statDictionary[PlayerStat.Speed].Init(0);
        statDictionary[PlayerStat.Strength].Init(0);
        statDictionary[PlayerStat.Life].Init(0);
        statDictionary[PlayerStat.WeaponA].Init(0);
        statDictionary[PlayerStat.WeaponB].Init(0);
        statDictionary[PlayerStat.WeaponC].Init(0);
        statDictionary[PlayerStat.WeaponD].Init(0);
        statDictionary[PlayerStat.Hp].Init(100);
        statDictionary[PlayerStat.HpMax].Init(100);
        statDictionary[PlayerStat.Exp].Init(0);
        statDictionary[PlayerStat.ExpMax].Init(20);

        //statDictionary[PlayerStat.ExpMax].Init(99999);
        //for (int i = 0; i < 8; i++)
        //{
        //    weaponContainers[0].GetComponent<WeaponContainerA>().StrengthenFirst();
        //    statDictionary[PlayerStat.WeaponA].Increase();
        //    weaponContainers[1].GetComponent<WeaponContainerB>().StrengthenFirst();
        //    statDictionary[PlayerStat.WeaponB].Increase();
        //    weaponContainers[2].GetComponent<WeaponContainerC>().StrengthenFirst();
        //    statDictionary[PlayerStat.WeaponC].Increase();
        //    weaponContainers[3].GetComponent<WeaponContainerD>().StrengthenFirst();
        //    statDictionary[PlayerStat.WeaponD].Increase();
        //}
        switch (StaticValues.playerCharacterNum)
        {
            case 0:
                weaponContainers[0].GetComponent<WeaponContainerA>().StrengthenFirst();
                statDictionary[PlayerStat.WeaponA].Increase();
                statDictionary[PlayerStat.Strength].Increase();
                break;
            case 1:
                weaponContainers[1].GetComponent<WeaponContainerB>().StrengthenFirst();
                statDictionary[PlayerStat.WeaponB].Increase();
                statDictionary[PlayerStat.Speed].Increase();
                break;
            case 2:
                weaponContainers[2].GetComponent<WeaponContainerC>().StrengthenFirst();
                statDictionary[PlayerStat.WeaponC].Increase();
                statDictionary[PlayerStat.Magnet].Increase();
                break;
            case 3:
                weaponContainers[3].GetComponent<WeaponContainerD>().StrengthenFirst();
                statDictionary[PlayerStat.WeaponD].Increase();
                statDictionary[PlayerStat.Life].Increase();
                break;
            default:
                break;
        }

        hpGuage.fillAmount = 1f;
        expGuage.fillAmount = 0f;

        magnetToggle.Init(isMagnetVisible);
    }
    private void FixedUpdate()
    {
        if (Time.timeScale == 0)
        {
            return;
        }
#if !UNITY_EDITOR
        moveVec = new Vector3(joystick.Horizontal, joystick.Vertical, 0f) * speed;
        transform.position += moveVec;
        spriteRenderer.flipX = moveVec.x < 0;

        float angle = Mathf.Atan2(joystick.Vertical, joystick.Horizontal) * Mathf.Rad2Deg;
        weaponContainers[1].rotation = Quaternion.Euler(0, 0, angle);
#else
        transform.position += moveVec;
#endif
    }
    public void OnClickMagnetVisibility()
    {
        isMagnetVisible = !isMagnetVisible;
        magnetRenderer.enabled = isMagnetVisible;
        magnetToggle.Init(isMagnetVisible);
    }
    public void KillEnemy()
    {
        statDictionary[PlayerStat.Kill].Increase();
    }
    public void GainExp(int value)
    {
        int exp = statDictionary[PlayerStat.Exp].value;
        int expMax = statDictionary[PlayerStat.ExpMax].value;

        exp += value;

        if (exp >= expMax)
        {
            exp -= expMax;
            expMax = (int)(expMax * 1.1f);

            statDictionary[PlayerStat.Level].Increase();
            statDictionary[PlayerStat.ExpMax].Init(expMax);

            // 입력 초기화
            var pointerData = new PointerEventData(EventSystem.current)
            {
                pointerId = -1,
                position = Input.mousePosition
            };
            ExecuteEvents.Execute<IPointerUpHandler>(joystick.gameObject, pointerData, ExecuteEvents.pointerUpHandler);
            ExecuteEvents.Execute<IEndDragHandler>(joystick.gameObject, pointerData, ExecuteEvents.endDragHandler);

            //
            GameCtrl.Instance.OnLevelUp();
            EnemyContainer.Instance.OnLevelUp();
            AudioManager.Instance.PlaySFX(SoundKey.PlayerLevelUp);
        }

        statDictionary[PlayerStat.Exp].Init(exp);
        expGuage.fillAmount = exp / (float)expMax;
    }
    public void GainReward(RewardInfo rewardInfo)
    {
        switch (rewardInfo.id)
        {
            case 0:
                statDictionary[PlayerStat.WeaponA].Increase();
                weaponContainers[0].GetComponent<WeaponContainerA>().StrengthenFirst();
                break;
            case 1:
                statDictionary[PlayerStat.WeaponA].Increase();
                weaponContainers[0].GetComponent<WeaponContainerA>().StrengthenSecond();
                break;
            case 10:
                statDictionary[PlayerStat.WeaponB].Increase();
                weaponContainers[1].GetComponent<WeaponContainerB>().StrengthenFirst();
                break;
            case 11:
                statDictionary[PlayerStat.WeaponB].Increase();
                weaponContainers[1].GetComponent<WeaponContainerB>().StrengthenSecond();
                break;
            case 20:
                statDictionary[PlayerStat.WeaponC].Increase();
                weaponContainers[2].GetComponent<WeaponContainerC>().StrengthenFirst();
                break;
            case 21:
                statDictionary[PlayerStat.WeaponC].Increase();
                weaponContainers[2].GetComponent<WeaponContainerC>().StrengthenSecond();
                break;
            case 30:
                statDictionary[PlayerStat.WeaponD].Increase();
                weaponContainers[3].GetComponent<WeaponContainerD>().StrengthenFirst();
                break;
            case 31:
                statDictionary[PlayerStat.WeaponD].Increase();
                weaponContainers[3].GetComponent<WeaponContainerD>().StrengthenSecond();
                break;
            case 90:
                statDictionary[PlayerStat.Life].Increase();
                break;
            case 91:
                magnetArea.localScale *= 1.1f;
                statDictionary[PlayerStat.Magnet].Increase();
                break;
            case 92:
                speed *= 1.1f;
                statDictionary[PlayerStat.Speed].Increase();
                break;
            case 93:
                statDictionary[PlayerStat.Strength].Increase();
                break;
        }
    }
    public virtual void OnDamage(int damage)
    {
        int hp = statDictionary[PlayerStat.Hp].value;
        int hpMax = statDictionary[PlayerStat.HpMax].value;

        hp -= damage;

        if (hp > 0)
        {
            canvasGO.SetActive(true);
            hpGuage.fillAmount = (float)hp / (float)hpMax;

            animator.SetTrigger("doHit");

            statDictionary[PlayerStat.Hp].Init(hp);
        }
        else
        {
            GameCtrl.Instance.OnGameEnd();
        }
    }
    private void OnMove(InputValue value)
    {
        Vector2 v = value.Get<Vector2>();

        if (v.sqrMagnitude > 0.001f)
        {
            moveVec = new Vector3(v.x, v.y, 0f) * speed;
            animator.SetBool("isMove", true);

            float angle = Mathf.Atan2(v.y, v.x) * Mathf.Rad2Deg;
            weaponContainers[1].rotation = Quaternion.Euler(0, 0, angle);

            spriteRenderer.flipX = moveVec.x < 0;
        }
        else
        {
            moveVec = Vector3.zero;
            animator.SetBool("isMove", false);
        }
    }

    [System.Serializable]
    public class StatSlot
    {
        public PlayerStat type;
        public TextMeshProUGUI TextUI;
        public int maxValue = int.MaxValue;
        public int value { get; private set; }

        public void Init(int value)
        {
            this.value = Mathf.Min(value, maxValue);

            if (TextUI != null)
            {
                TextUI.text = this.value == maxValue ? "MAX" : this.value.ToString();
            } 
        }
        public void Increase(int value = 1)
        {
            this.value = Mathf.Min(this.value + value, maxValue);

            if (TextUI != null)
            {
                TextUI.text = this.value == maxValue ? "MAX" : this.value.ToString();
            }
        }
        public bool TryIncrease(int value = 1)
        {
            if (this.value < maxValue)
            {
                Increase(value);

                return true;
            }

            return false;
        }
    }
    public enum PlayerStat 
    { 
        Level, 
        Kill, 
        Life, 
        Strength, 
        Speed, 
        Magnet, 
        WeaponA, 
        WeaponB, 
        WeaponC, 
        WeaponD,
        Hp,
        HpMax,
        Exp,
        ExpMax
    }
}
